// Build src/styles/fonts.css: the Latin Cabin faces from Google Fonts, inlined as
// base64 woff2.

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

const FAMILIES = [
  { name: 'Cabin', axis: 'wght@400..700' },
  { name: 'Cabin Condensed', axis: 'wght@700' },
];

// Google Fonts serves woff2 only to user agents it recognises.
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const LICENCE = `/*
 * Cabin and Cabin Condensed, by Pablo Impallari, Rodrigo Fuenzalida and Igino
 * Marini. Licensed under the SIL Open Font License, Version 1.1:
 * https://openfontlicense.org
 *
 * GENERATED by scripts/build-fonts.mjs (just map::fonts) — do not edit.
 * Latin subset only; the woff2 is inlined so the widget stays one file and
 * contacts no font service at runtime.
 */
`;

const OUT = join(import.meta.dirname, '..', 'src', 'styles', 'fonts.css');

async function get(url) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`fetch failed HTTP ${res.status} (${url})`);
  return res;
}

async function fetchCss(family) {
  const spec = `${family.name.replace(/ /g, '+')}:${family.axis}`;
  return (await get(`https://fonts.googleapis.com/css2?family=${spec}&display=swap`)).text();
}

function faceBlocks(css) {
  return [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)].map(
    ([, subset, block]) => ({ subset, block }),
  );
}

function field(block, name) {
  return block.match(new RegExp(`${name}:\\s*([^;]+);`))?.[1]?.trim();
}

async function inlineFace(block) {
  const url = field(block, 'src')?.match(/url\((https:[^)]+)\)/)?.[1];
  if (!url) throw new Error(`no woff2 url in: ${block.slice(0, 80)}`);
  const woff2 = Buffer.from(await (await get(url)).arrayBuffer());

  return {
    bytes: woff2.length,
    css: [
      '@font-face {',
      `  font-family: ${field(block, 'font-family')};`,
      `  font-style: ${field(block, 'font-style')};`,
      `  font-weight: ${field(block, 'font-weight')};`,
      '  font-display: swap;',
      `  src: url(data:font/woff2;base64,${woff2.toString('base64')}) format('woff2');`,
      `  unicode-range: ${field(block, 'unicode-range')};`,
      '}',
    ].join('\n'),
  };
}

const faces = [];
let woff2Bytes = 0;

for (const family of FAMILIES) {
  const blocks = faceBlocks(await fetchCss(family)).filter((b) => b.subset === 'latin');
  if (blocks.length !== 1) {
    throw new Error(
      `${family.name}: expected one latin face from a variable axis, got ${blocks.length}`,
    );
  }
  const face = await inlineFace(blocks[0].block);
  woff2Bytes += face.bytes;
  faces.push(face.css);
  console.log(`${family.name}: ${(face.bytes / 1024).toFixed(1)} KB of woff2`);
}

const css = LICENCE + '\n' + faces.join('\n\n') + '\n';
writeFileSync(OUT, css);
const kb = (n) => `${(n / 1024).toFixed(0)} KB`;
console.log(
  `wrote ${faces.length} faces to ${OUT} (${kb(woff2Bytes)} of woff2, ${kb(css.length)} as base64)`,
);
