import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const FAMILIES = [
  { name: 'Cabin', axis: 'wght@400..700' },
  { name: 'Cabin Condensed', axis: 'wght@700' },
];

const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const LICENCE = `/*
 * Cabin and Cabin Condensed, by Pablo Impallari, Rodrigo Fuenzalida and Igino
 * Marini. Licensed under the SIL Open Font License, Version 1.1:
 * https://openfontlicense.org
 *
 * GENERATED by scripts/build-fonts.mjs (just map::fonts) — do not edit.
 * Latin subset only; the woff2 is inlined so the widget stays one file and
 * contacts no font service at runtime.
 */
`;

async function fetchCss(family) {
  const spec = `${family.name.replace(/ /g, '+')}:${family.axis}`;
  const url = `https://fonts.googleapis.com/css2?family=${spec}&display=swap`;
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`fetch failed HTTP ${res.status} (${url})`);
  return res.text();
}

function faceBlocks(css) {
  return [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)].map(
    ([, subset, block]) => ({ subset, block }),
  );
}

function field(block, name) {
  return block.match(new RegExp(`${name}:\\s*([^;]+);`))?.[1]?.trim();
}

async function inlineFace(block) {
  const url = field(block, 'src')?.match(/url\((https:[^)]+)\)/)?.[1];
  if (!url) throw new Error(`no woff2 url in: ${block.slice(0, 80)}`);

  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`fetch failed HTTP ${res.status} (${url})`);
  const bytes = Buffer.from(await res.arrayBuffer());

  const family = field(block, 'font-family');
  const weight = field(block, 'font-weight');
  const style = field(block, 'font-style');
  const range = field(block, 'unicode-range');

  return {
    bytes: bytes.length,
    css: [
      '@font-face {',
      `  font-family: ${family};`,
      `  font-style: ${style};`,
      `  font-weight: ${weight};`,
      '  font-display: swap;',
      `  src: url(data:font/woff2;base64,${bytes.toString('base64')}) format('woff2');`,
      `  unicode-range: ${range};`,
      '}',
    ].join('\n'),
  };
}

async function main() {
  const faces = [];
  let raw = 0;

  for (const family of FAMILIES) {
    const blocks = faceBlocks(await fetchCss(family)).filter((b) => b.subset === 'latin');
    if (blocks.length !== 1) {
      throw new Error(
        `${family.name}: expected one latin face from a variable axis, got ${blocks.length}`,
      );
    }
    const face = await inlineFace(blocks[0].block);
    raw += face.bytes;
    faces.push(face.css);
    console.log(`${family.name}: ${(face.bytes / 1024).toFixed(1)} KB of woff2`);
  }

  const out = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'styles', 'fonts.css');
  const css = LICENCE + '\n' + faces.join('\n\n') + '\n';
  writeFileSync(out, css);
  console.log(
    `wrote ${faces.length} faces to ${out}` +
      ` (${(raw / 1024).toFixed(0)} KB of woff2, ${(css.length / 1024).toFixed(0)} KB as base64)`,
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
